#!/usr/bin/env node
/*
 * The careers domain icons: the pinned set, drawn.
 *
 * Paddock lets staff give each careers domain (Electronics, Software, ...) one icon, chosen
 * from a closed list of lucide names (DOMAIN_ICONS in Paddock's src/lib/careers/domains.js).
 * The website has no lucide dependency, so it keeps its own copy of exactly that list,
 * tools/source/careers-icons.json, and this script turns it into assets/careers-icons.js: a
 * small map of name to SVG markup, drawn the way every icon on the site is (24 grid,
 * stroke 1.6, currentColor, round caps). The generated file is committed, so neither the
 * build nor a page ever needs lucide.
 *
 *   npm run icons                          regenerate from the Paddock repo's lucide-react
 *   node tools/source/icons.mjs --from <dir>   from any lucide-react or lucide package folder
 *                                          (LUCIDE_DIR works too)
 *   node tools/source/icons.mjs --check    every pinned name is drawn (no lucide needed)
 *
 * When Paddock adds a name to DOMAIN_ICONS: add it to the JSON, run this, commit both. A
 * name the site does not have renders as a neutral dot, never as nothing, so a page is never
 * broken by the two lists drifting, only plainer.
 *
 * Importable: loadIcons() reads the generated file the way a page would (the build uses it
 * to draw a role's domain icon into the static page), and checkIcons() is the --check.
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
export const ICONS_JSON = path.join(HERE, 'careers-icons.json');
export const ICONS_JS = path.join(REPO, 'assets/careers-icons.js');

// Where lucide is looked for when no folder is named: the Paddock checkout next to this one.
const CANDIDATES = [
  path.resolve(REPO, '../App Builds/CentralLedgerOnGCP-paddockProduction/node_modules/lucide-react'),
  path.resolve(REPO, '../App Builds/CentralLedgerOnGCP-paddockProduction/node_modules/lucide'),
  path.resolve(REPO, 'node_modules/lucide-react'),
  path.resolve(REPO, 'node_modules/lucide'),
];

const ALLOWED_TAGS = new Set(['path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse']);
const ALLOWED_ATTRS = new Set(['d', 'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'x1', 'y1', 'x2', 'y2', 'width', 'height', 'points']);

export const pinnedNames = () => JSON.parse(fs.readFileSync(ICONS_JSON, 'utf8'));

/** The bracketed array literal that starts at text[start] ('['), by matching brackets. */
function arrayAt(text, start) {
  let depth = 0;
  let quote = '';
  for (let i = start; i < text.length; i++) {
    const c = text[i];
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = '';
      continue;
    }
    if (c === '"' || c === "'" || c === '`') quote = c;
    else if (c === '[') depth++;
    else if (c === ']' && --depth === 0) return text.slice(start, i + 1);
  }
  return null;
}

/** One icon's nodes, [[tag, attrs], ...], read from a lucide or lucide-react module file. */
function readNodes(dir, name) {
  const file = path.join(dir, 'dist/esm/icons', `${name}.js`);
  if (!fs.existsSync(file)) return null;
  const text = fs.readFileSync(file, 'utf8');
  // lucide-react: const __iconNode = [...]. lucide: const Name = [...].
  const m = /const\s+(?:__iconNode|[A-Z]\w*)\s*=\s*\[/.exec(text);
  if (!m) return null;
  const literal = arrayAt(text, m.index + m[0].length - 1);
  if (!literal) return null;
  // A data literal from a pinned package, evaluated with nothing in scope.
  const nodes = vm.runInNewContext(`(${literal})`, Object.create(null), { timeout: 200 });
  return Array.isArray(nodes) ? nodes : null;
}

const escAttr = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

/** Nodes as the markup inside an <svg>, with lucide's React keys dropped. */
function markup(nodes) {
  return nodes.map(([tag, attrs]) => {
    if (!ALLOWED_TAGS.has(tag)) throw new Error(`unexpected element <${tag}>`);
    const a = Object.entries(attrs || {})
      .filter(([k]) => ALLOWED_ATTRS.has(k))
      .map(([k, v]) => ` ${k}="${escAttr(v)}"`).join('');
    return `<${tag}${a}/>`;
  }).join('');
}

function lucideVersion(dir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')).version || '';
  } catch {
    return '';
  }
}

function generated(icons, source) {
  const entries = Object.entries(icons).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
  return `/*
 * The careers domain icons. GENERATED by tools/source/icons.mjs from ${source}
 * (ISC licence, https://lucide.dev). Do not edit: change tools/source/careers-icons.json,
 * which mirrors DOMAIN_ICONS in Paddock, and run npm run icons.
 *
 * Shared by every careers page (the timeline on careers.html, the role pages, the apply
 * sheet), and by the build, which draws a role's domain icon into its static page:
 *
 *   gridIcons.names                     the pinned names, in Paddock's order
 *   gridIcons.has(name)                 whether the set draws it
 *   gridIcons.svg(name, opts)           an <svg> as markup (a constant: safe for innerHTML)
 *   gridIcons.element(name, opts)       the same, as an element
 *     opts: { size = 24, className = '', label = '' }  a label makes it role="img"
 *
 * Every icon is drawn as the site draws its own: a 24 unit grid, a 1.6 stroke in
 * currentColor, round caps and joins, no fill. A name the set does not have (Paddock's list
 * grew before this one did) draws a neutral dot, so a domain is never left without a mark.
 */
(() => {
  'use strict';

  const ICONS = {
${entries}
  };
  const DOT = '<circle cx="12" cy="12" r="3" fill="currentColor" stroke="none"/>';
  const has = (name) => Object.prototype.hasOwnProperty.call(ICONS, name);
  const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  function svg(name, { size = 24, className = '', label = '' } = {}) {
    const a11y = label ? \` role="img" aria-label="\${esc(label)}"\` : ' aria-hidden="true"';
    const cls = className ? \` class="\${esc(className)}"\` : '';
    const n = Number(size) > 0 ? Number(size) : 24;
    return \`<svg\${cls} viewBox="0 0 24 24" width="\${n}" height="\${n}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" focusable="false"\${a11y}>\${has(name) ? ICONS[name] : DOT}</svg>\`;
  }

  function element(name, opts) {
    const t = document.createElement('template');
    t.innerHTML = svg(name, opts); // built only from the constants above and escaped options
    return t.content.firstElementChild;
  }

  const api = { names: Object.freeze(Object.keys(ICONS)), has, svg, element };
  if (typeof window !== 'undefined') window.gridIcons = api;
})();
`;
}

/** What the generated file says, run the way a page runs it. */
export function loadIcons(file = ICONS_JS) {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(file, 'utf8'), sandbox, { filename: file, timeout: 1000 });
  return sandbox.window.gridIcons;
}

/** Every pinned name drawn, and nothing drawn that is not pinned. */
export function checkIcons() {
  const names = pinnedNames();
  const icons = loadIcons();
  const missing = names.filter((n) => !icons.has(n));
  const extra = icons.names.filter((n) => !names.includes(n));
  return { names, missing, extra, ok: !missing.length && !extra.length };
}

function generate(dir) {
  const names = pinnedNames();
  const icons = {};
  const missing = [];
  for (const name of names) {
    const nodes = readNodes(dir, name);
    if (!nodes) missing.push(name);
    else icons[name] = markup(nodes);
  }
  if (missing.length) throw new Error(`lucide at ${dir} has no ${missing.join(', ')}`);
  const pkg = path.basename(dir);
  const version = lucideVersion(dir);
  fs.writeFileSync(ICONS_JS, generated(icons, `${pkg}${version ? ` v${version}` : ''}`));
  return { count: names.length, file: path.relative(REPO, ICONS_JS) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.includes('--check')) {
    const r = checkIcons();
    if (r.missing.length) console.error(`careers icons: not drawn: ${r.missing.join(', ')} (run npm run icons)`);
    if (r.extra.length) console.error(`careers icons: drawn but not pinned: ${r.extra.join(', ')} (run npm run icons)`);
    if (r.ok) console.log(`careers icons: all ${r.names.length} pinned names drawn`);
    process.exitCode = r.ok ? 0 : 1;
  } else {
    const i = args.indexOf('--from');
    const named = (i >= 0 && args[i + 1]) || process.env.LUCIDE_DIR || '';
    const dir = named ? path.resolve(named) : CANDIDATES.find((d) => fs.existsSync(path.join(d, 'dist/esm/icons')));
    if (!dir || !fs.existsSync(path.join(dir, 'dist/esm/icons'))) {
      console.error('No lucide found. Name a lucide-react (or lucide) package folder with --from <dir>.');
      process.exit(1);
    }
    const r = generate(dir);
    console.log(`${r.file}: ${r.count} icons from ${dir}`);
  }
}
